/* V66-UX10 */
(function(){'use strict';
var v66StatusTimer=null,v66UndoTimer=null;
function v66SetStatus(text,kind,hold){
 var el=document.getElementById('v66-status-hud');
 if(!el){el=document.createElement('div');el.id='v66-status-hud';el.setAttribute('role','status');el.setAttribute('aria-live','polite');el.innerHTML='<span id="v66-status-dot"></span><span id="v66-status-text"></span>';document.body.appendChild(el);}
 el.dataset.kind=kind||'working';var t=document.getElementById('v66-status-text');if(t)t.textContent=String(text||'');el.classList.add('show');clearTimeout(v66StatusTimer);if(!hold)v66StatusTimer=setTimeout(function(){el.classList.remove('show')},kind==='error'?4200:2200);
}
window.v66SetStatus=v66SetStatus;
function v66MountAIQuick(){var form=document.getElementById('ai-chat-form');if(!form||document.getElementById('v66-ai-quick'))return;var row=document.createElement('div');row.id='v66-ai-quick';[['힌트만','정답은 말하지 말고, 내가 스스로 풀 수 있도록 핵심 힌트만 단계적으로 줘.'],['풀이','이 문제를 개념부터 풀이 과정까지 이해하기 쉽게 설명해줘.'],['비슷한 문제','방금 내용과 같은 개념의 비슷한 문제를 1개 만들어줘. 정답은 내가 요청할 때 알려줘.'],['내 답 채점','내가 쓴 답을 채점하고, 틀린 부분만 짧게 고쳐줘. 내 답: ']].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='v66-ai-chip';b.textContent=x[0];b.addEventListener('click',function(){var input=document.getElementById('ai-chat-input-text');if(!input)return;input.value=x[1];input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();try{input.setSelectionRange(input.value.length,input.value.length)}catch(_){}});row.appendChild(b)});form.parentNode.insertBefore(row,form);}
function v66MountDock(){if(document.getElementById('v66-mobile-dock'))return;var dock=document.createElement('div');dock.id='v66-mobile-dock';[['📎','PDF',function(){var b=document.getElementById('study-note-pdf-btn');if(b)b.click()}],['✨','AI',function(){var b=document.getElementById('study-note-ai-btn');if(b)b.click()}],['👁','미리보기',function(){if(typeof window.toggleStudyNotePreview==='function')window.toggleStudyNotePreview()}],['✓','저장',function(){if(typeof window.saveCurrentStudyNote==='function'){v66SetStatus('노트 저장 중…','working',true);Promise.resolve(window.saveCurrentStudyNote()).finally(function(){v66SetStatus('저장됨','saved')})}}]].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='v66-dock-btn';b.innerHTML='<b>'+x[0]+'</b><span>'+x[1]+'</span>';b.addEventListener('click',x[2]);dock.appendChild(b)});document.body.appendChild(dock);}
function v66RenderHomeFocus(){var hero=document.getElementById('home-greeting');if(!hero||document.getElementById('v66-home-focus'))return;var card=hero.closest('.rounded-3xl');if(!card)return;var latest='최근 노트';try{if(Array.isArray(studyNotesCache)&&studyNotesCache.length){var n=studyNotesCache.slice().sort(function(a,b){return new Date(b.updated_at||0)-new Date(a.updated_at||0)})[0];if(n&&n.title)latest=String(n.title)}}catch(_){}var panel=document.createElement('div');panel.id='v66-home-focus';panel.innerHTML='<div class="v66-home-focus-head"><div><b>오늘 이어서 하기</b><br><span>자주 쓰는 학습 흐름을 바로 시작하세요.</span></div><span>빠른 시작</span></div><div class="v66-home-focus-grid"></div>';var grid=panel.querySelector('.v66-home-focus-grid');[[latest,'노트 이어쓰기','notes'],['오늘 틀린 문제','오답 다시 보기','wrong-notes'],['AI 최근 질문','학습 도우미 열기','ai-chat']].forEach(function(x){var b=document.createElement('button');b.type='button';b.className='v66-home-focus-btn';b.innerHTML='<strong></strong><small></small>';b.querySelector('strong').textContent=x[0];b.querySelector('small').textContent=x[1];b.addEventListener('click',function(){if(typeof window.navigate==='function')window.navigate(x[2])});grid.appendChild(b)});card.insertAdjacentElement('afterend',panel);}
function v66EnhanceEmpty(){var e=document.querySelector('#study-note-gallery-grid .study-note-gallery-empty');if(!e||e.querySelector('.v66-empty-actions')||e.textContent.indexOf('아직 노트가 없어요')<0)return;var a=document.createElement('div');a.className='v66-empty-actions';var n=document.createElement('button');n.type='button';n.className='v66-empty-action';n.textContent='첫 노트 만들기';n.addEventListener('click',function(){if(typeof window.newStudyNote==='function')window.newStudyNote()});var p=document.createElement('button');p.type='button';p.className='v66-empty-action secondary';p.textContent='PDF로 시작';p.addEventListener('click',function(){if(typeof window.newStudyNoteWithPdf==='function')window.newStudyNoteWithPdf()});var ai=document.createElement('button');ai.type='button';ai.className='v66-empty-action secondary';ai.textContent='AI에게 물어보기';ai.addEventListener('click',function(){if(typeof window.navigate==='function')window.navigate('ai-chat')});a.appendChild(n);a.appendChild(p);a.appendChild(ai);e.appendChild(a);}
function v66ShowUndo(label,onCommit){clearTimeout(v66UndoTimer);var old=document.getElementById('v66-undo');if(old)old.remove();var el=document.createElement('div');el.id='v66-undo';el.innerHTML='<span></span><button type="button">실행 취소</button>';el.querySelector('span').textContent=label+' · 5초 후 적용';var undone=false;el.querySelector('button').addEventListener('click',function(){undone=true;clearTimeout(v66UndoTimer);el.remove();v66SetStatus('삭제를 취소했어요.','saved')});document.body.appendChild(el);v66UndoTimer=setTimeout(function(){if(undone)return;el.remove();Promise.resolve().then(onCommit).catch(function(err){console.error('[V66 undo commit]',err);v66SetStatus('삭제하지 못했습니다.','error')})},5000)}
function v66PatchFunctions(){
 if(typeof window.setStudyNoteSaveState==='function'&&!window.setStudyNoteSaveState.__v66){var baseSave=window.setStudyNoteSaveState;var f=function(text,kind){var r=baseSave.apply(this,arguments);if(kind==='saving')v66SetStatus('노트 저장 중…','working',true);else if(kind==='saved')v66SetStatus('노트 저장됨','saved');else if(kind==='error')v66SetStatus(text||'저장 실패','error');else if(kind==='offline'||kind==='conflict')v66SetStatus(text||'기기에 임시 저장됨','working');return r};f.__v66=1;window.setStudyNoteSaveState=f;}
 if(typeof window.showAITypingIndicator==='function'&&!window.showAITypingIndicator.__v66){var baseTyping=window.showAITypingIndicator;var tf=function(){v66SetStatus('AI 답변 생성 중…','working',true);return baseTyping.apply(this,arguments)};tf.__v66=1;window.showAITypingIndicator=tf;}
 if(typeof window.hideAITypingIndicator==='function'&&!window.hideAITypingIndicator.__v66){var baseHide=window.hideAITypingIndicator;var hf=function(){var r=baseHide.apply(this,arguments);v66SetStatus('AI 답변 준비 완료','saved');return r};hf.__v66=1;window.hideAITypingIndicator=hf;}
 if(typeof window.studyNotePdfStage==='function'&&!window.studyNotePdfStage.__v66){var baseStage=window.studyNotePdfStage;var pf=function(holder,seq,stage,html){var r=baseStage.apply(this,arguments);if(holder&&holder.isConnected){var busy=['download','decode','connect','opening'].indexOf(stage)>=0;holder.querySelectorAll('.v66-pdf-skeleton,.v66-pdf-progress').forEach(function(x){x.remove()});if(busy){var sk=document.createElement('div');sk.className='v66-pdf-skeleton';sk.innerHTML='<span></span><span></span><span></span>';var pr=document.createElement('div');pr.className='v66-pdf-progress';pr.innerHTML='<i></i>';holder.prepend(pr);holder.prepend(sk);var label=stage==='download'?'PDF 불러오는 중':stage==='decode'?'PDF 분석 중':stage==='opening'?'1페이지 준비 중':'PDF 연결 중';v66SetStatus(label+'…','working',true)}}return r};pf.__v66=1;window.studyNotePdfStage=pf;}
 if(typeof window.renderStudyNoteGallery==='function'&&!window.renderStudyNoteGallery.__v66){var baseGal=window.renderStudyNoteGallery;var gf=function(){var r=baseGal.apply(this,arguments);v66EnhanceEmpty();return r};gf.__v66=1;window.renderStudyNoteGallery=gf;}
 if(typeof window.renderStudyNotes==='function'&&!window.renderStudyNotes.__v66){var baseNotes=window.renderStudyNotes;var nf=async function(){var r=await baseNotes.apply(this,arguments);v66EnhanceEmpty();return r};nf.__v66=1;window.renderStudyNotes=nf;}
 if(typeof window.renderHomeDashboard==='function'&&!window.renderHomeDashboard.__v66){var baseHome=window.renderHomeDashboard;var hmf=async function(){var r=await baseHome.apply(this,arguments);v66RenderHomeFocus();return r};hmf.__v66=1;window.renderHomeDashboard=hmf;}
 if(typeof window.renderAIChatView==='function'&&!window.renderAIChatView.__v66){var baseAI=window.renderAIChatView;var aif=async function(){var r=await baseAI.apply(this,arguments);v66MountAIQuick();return r};aif.__v66=1;window.renderAIChatView=aif;}
 if(typeof window.setStudyNoteMode==='function'&&!window.setStudyNoteMode.__v66){var baseMode=window.setStudyNoteMode;var mf=function(mode){try{localStorage.setItem('nw_v66_note_mode',String(mode||'text'))}catch(_){}return baseMode.apply(this,arguments)};mf.__v66=1;window.setStudyNoteMode=mf;}
 if(typeof window.newStudyNote==='function'&&!window.newStudyNote.__v66){var baseNew=window.newStudyNote;var nw=async function(){var remembered='text';try{remembered=localStorage.getItem('nw_v66_note_mode')||'text'}catch(_){}var r=await baseNew.apply(this,arguments);if(remembered==='ink'&&typeof window.setStudyNoteMode==='function')window.setStudyNoteMode('ink');else{var body=document.getElementById('study-note-body');setTimeout(function(){if(body&&!(document.getElementById('study-note-title')||{}).value)body.focus()},120)}return r};nw.__v66=1;window.newStudyNote=nw;}
 window.deleteCurrentStudyNote=async function(){if(!currentStudyNoteId){if(typeof window.newStudyNote==='function')window.newStudyNote();return}var ok=await window.showConfirm({title:'노트를 삭제할까요?',message:'5초 동안 실행 취소할 수 있어요. 이후 휴지통으로 이동합니다.'});if(!ok)return;var id=currentStudyNoteId;v66ShowUndo('노트 삭제',async function(){var c=window.getSupabase(),u=await window.getCurrentAuthUser();if(!c||!u)return;var q=await c.from('study_notes').update({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',u.id);if(q.error){if(typeof window.reportStudyNoteTechnicalError==='function')window.reportStudyNoteTechnicalError(q.error,'노트를 삭제하지 못했습니다.');return}studyNotesCache=(studyNotesCache||[]).filter(function(n){return String(n.id)!==String(id)});if(String(currentStudyNoteId)===String(id))currentStudyNoteId=null;if(typeof window.renderStudyNoteListOnly==='function')window.renderStudyNoteListOnly();if(typeof window.renderStudyNoteGallery==='function')window.renderStudyNoteGallery((document.getElementById('study-note-gallery-search')||{}).value||'');if(typeof window.showStudyNoteGallery==='function')window.showStudyNoteGallery();v66SetStatus('휴지통으로 이동했어요.','saved')})};
 window.removeStudyNotePdf=async function(id){var a=(studyNotePdfAttachments||[]).find(function(x){return String(x.id)===String(id)});if(!a)return;var ok=await window.showConfirm({title:'PDF를 삭제할까요?',message:'5초 동안 실행 취소할 수 있어요.'});if(!ok)return;v66ShowUndo('PDF 삭제',async function(){var c=window.getSupabase(),u=await window.getCurrentAuthUser();if(!c||!u)return;var del=await c.from('study_note_attachments').delete().eq('id',id).eq('user_id',u.id);if(del.error){if(typeof window.reportStudyNoteTechnicalError==='function')window.reportStudyNoteTechnicalError(del.error,'PDF를 삭제하지 못했습니다.');return}try{await c.storage.from('study-note-pdfs').remove([a.storage_path])}catch(_){}try{studyNotePdfLocalFiles.delete(String(id))}catch(_){}studyNotePdfAttachments=(studyNotePdfAttachments||[]).filter(function(x){return String(x.id)!==String(id)});if(typeof window.syncStudyNotePdfCacheMeta==='function')window.syncStudyNotePdfCacheMeta(currentStudyNoteId);if(typeof window.renderStudyNoteListOnly==='function')window.renderStudyNoteListOnly();if(typeof window.renderStudyNotePdfAttachments==='function')await window.renderStudyNotePdfAttachments();v66SetStatus('PDF를 삭제했어요.','saved')})};
}
function v66Mount(){v66PatchFunctions();v66MountAIQuick();v66MountDock();v66RenderHomeFocus();v66EnhanceEmpty();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',v66Mount,{once:true});else v66Mount();
window.addEventListener('load',function(){v66Mount();setTimeout(v66Mount,500)});
})();